spring:
  application:
    name: tinsiag-ai-code-mother

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://home.tinsiag.cn:4406/tinsiag_ai_code_mother
    username: admin
    password: 123456
  profiles:
    active: local

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.tinsiag.tinsiagaicodemother.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
