spring:
  application:
    name: tinsiag-ai-code-mother
  session:
    store-type: redis
    timeout: 3592000
    redis:
      namespace: tinsiag-ai-code-mother:session

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://home.tinsiag.cn:4406/tinsiag_ai_code_mother
    username: admin
    password: 123456
    hikari:
      max-lifetime: 300000
      keepalive-time: 120000
#  redis
  profiles:
    active: local
  data:
    redis:
      host: home.tinsiag.cn
      port: 6380
      ttl: 3600
      prefix: "tinsiag-ai-code-mother:"
      password: fuckredis123
      user: default
      database: 0

server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 3592000
# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.tinsiag.tinsiagaicodemother.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
